import Link from 'next/link';
import { ArrowLeft, ShieldCheck, Mail, Phone, MapPin, Building } from 'lucide-react';

export const metadata = {
  title: 'Terms & Conditions | ProfitupX',
  description: 'Terms and conditions for using ProfitupX platform operated by PANDI GANESH BABU.',
};

export default function TermsPage() {
  return (
    <div style={{ backgroundColor: '#fff', minHeight: '100vh', color: '#111', fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
      {/* Top Header Nav */}
      <header style={{ borderBottom: '1px solid #eaeaea', padding: '16px 24px', backgroundColor: '#fafafa' }}>
        <div style={{ maxWidth: '1100px', margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: '8px', textDecoration: 'none' }}>
            <img src="/icon.png" alt="ProfitupX" style={{ width: '28px', height: '28px', borderRadius: '6px' }} />
            <span style={{ fontWeight: 900, fontSize: '1.2rem', color: '#000', letterSpacing: '-0.5px' }}>ProfitupX</span>
          </Link>
          <div style={{ display: 'flex', gap: '20px', fontSize: '0.88rem', fontWeight: 600 }}>
            <Link href="/" style={{ color: '#555', textDecoration: 'none' }}>Home</Link>
            <Link href="/about" style={{ color: '#555', textDecoration: 'none' }}>About</Link>
            <Link href="/pricing" style={{ color: '#555', textDecoration: 'none' }}>Pricing</Link>
            <Link href="/contact" style={{ color: '#555', textDecoration: 'none' }}>Contact</Link>
          </div>
        </div>
      </header>

      <div style={{ maxWidth: '850px', margin: '0 auto', padding: '50px 24px 80px' }}>
        <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', color: '#666', textDecoration: 'none', marginBottom: '32px', fontWeight: 600, fontSize: '0.9rem' }}>
          <ArrowLeft size={16} /> Back to Home
        </Link>
        
        <h1 style={{ fontSize: '2.4rem', fontWeight: 900, letterSpacing: '-0.04em', marginBottom: '16px', color: '#000' }}>Terms & Conditions</h1>
        <p style={{ color: '#666', fontSize: '0.95rem', marginBottom: '32px' }}>Last updated: September 10, 2026</p>

        {/* Legal Merchant Notice Box */}
        <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '16px', padding: '24px', marginBottom: '36px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 800, color: '#0f172a', fontSize: '1rem' }}>
            <ShieldCheck size={20} color="#0284c7" /> Legal Entity & Merchant Details
          </div>
          <p style={{ fontSize: '0.9rem', color: '#475569', lineHeight: 1.6, margin: 0 }}>
            This Platform (<strong>ProfitupX</strong> - https://profitupx.com) is owned and operated by <strong>PANDI GANESH BABU</strong> (hereinafter referred to as &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '12px', marginTop: '8px', fontSize: '0.88rem', color: '#334155' }}>
            <div><strong>Legal Entity Name:</strong> PANDI GANESH BABU</div>
            <div><strong>Trade / Brand Name:</strong> ProfitupX</div>
            <div><strong>Official Email:</strong> ganeshdon5555@gmail.com</div>
            <div><strong>Official Contact:</strong> +91 8098824262</div>
            <div style={{ gridColumn: '1 / -1' }}><strong>Registered Address:</strong> KPT Nagar, Ayyampalayam, Dindigul, Tamil Nadu - 624601, India</div>
          </div>
        </div>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '22px', fontSize: '0.95rem', lineHeight: 1.8, color: '#333' }}>
          <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

          <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://profitupx.com (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).</p>

          <p>The Platform is owned and managed by <strong>PANDI GANESH BABU</strong>, with its principal office at KPT Nagar, Ayyampalayam, Dindigul, Tamil Nadu - 624601 (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).</p>

          <p>Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.</p>

          <h2 style={{ fontSize: '1.3rem', fontWeight: 800, marginTop: '20px', color: '#000' }}>1. Use of Services & Account Registration</h2>
          <ul style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
            <li>You agree and understand that you are responsible for maintaining the confidentiality of your password and credentials.</li>
            <li>You agree to pay us the platform service charges associated with availing the payment aggregation and store hosting services.</li>
          </ul>

          <h2 style={{ fontSize: '1.3rem', fontWeight: 800, marginTop: '20px', color: '#000' }}>2. Payments & Settlements</h2>
          <p>All online payments on ProfitupX are processed through authorized and RBI-compliant payment gateway partners, including Cashfree Payments. Settlements to creators/sellers are executed into their verified Indian Bank Account or UPI VPA in compliance with NPCI and RBI payment aggregator guidelines.</p>

          <h2 style={{ fontSize: '1.3rem', fontWeight: 800, marginTop: '20px', color: '#000' }}>3. Prohibited Activities</h2>
          <p>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, fraudulent, or forbidden by these Terms, or Indian or local laws that might apply to you, including but not limited to selling counterfeit items, prohibited goods, infringing intellectual property, or engaging in unauthorized financial activities.</p>

          <h2 style={{ fontSize: '1.3rem', fontWeight: 800, marginTop: '20px', color: '#000' }}>4. Governing Law & Dispute Resolution</h2>
          <p>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Dindigul / Madurai, Tamil Nadu, India.</p>

          <h2 style={{ fontSize: '1.3rem', fontWeight: 800, marginTop: '20px', color: '#000' }}>5. Contact Information</h2>
          <p>If you have any questions or grievances regarding these Terms & Conditions, you may contact us at:</p>
          <div style={{ background: '#f8fafc', padding: '16px 20px', borderRadius: '12px', border: '1px solid #e2e8f0', fontSize: '0.9rem', lineHeight: 1.6 }}>
            <strong>Legal Name:</strong> PANDI GANESH BABU<br />
            <strong>Platform:</strong> ProfitupX (https://profitupx.com)<br />
            <strong>Email:</strong> ganeshdon5555@gmail.com<br />
            <strong>Phone:</strong> +91 8098824262<br />
            <strong>Address:</strong> KPT Nagar, Ayyampalayam, Dindigul, Tamil Nadu - 624601, India
          </div>
        </div>
      </div>
    </div>
  );
}
